### ISSUE TITLE
[BUG][1.12.2] Certus Quartz Ore drops Quartz

### ISSUE THREAD

**Issue by Peter-Pwn** [Rohzek/SimpleOreGeneration#26]
I'm using SimpleOreGeneration 4.2.1 and breaking Certus Quartz Ore drops Quartz from SimpleOreGeneration.

After looking at your code, it looks like you are overwriting Certus with your own, because of the alphabetical order of surfaceOres (also end+nether) in SGOres.java. Calling SGOres.getBlockSurface("quartz") returns the first block containing quartz and this is Certus.

Charged Certus is working fine, but it drops as block. They should drop crystals.

**Comment by Rohzek** [comment]
Fixed in 4.3.0

**Comment by Peter-Pwn** [comment]
In the new version (4.3.1) you forgot to add "new SurfaceOreBlock("surfaceCertusQuartzOre")" and		"new SurfaceOreBlock("surfaceChargedCertusQuartzOre")". Nether and end ores are working fine.
